/**
 * NIZAM · Transaction model — mirrors NIZAM ledger schema
 * Implemented by: KIRO Contract 1 / Phase 1.5
 * Extended by: Contract 6 (multicurrency ledger integrity) / Phase 6.4 — versioned
 *   allocation sets and the reconciled lock (I4.1-I4.6), owner decision D4-A
 *   (reversal + replacement) ratified 2026-09-02.
 * Depends on: lib/money/money.ts
 *
 * Signed convention (money-rules.md): outflow negative, inflow positive in `amount`.
 */
import type { Money } from '@/lib/money/money';
import type { CurrencyCode } from '@/lib/money/currency';

export const CLEARED_STATUSES = ['uncleared', 'cleared', 'reconciled'] as const;
export type ClearedStatus = (typeof CLEARED_STATUSES)[number];

/** One leg of a split transaction. Split amounts sum exactly to the parent amount. */
export interface TransactionSplit {
  id: string;
  categoryId: string | null;
  amount: Money;
  memo: string;
}

/**
 * A retained, superseded allocation set (C6 I4.4, vNext A4).
 *
 * Editing a split is an atomic versioned mutation: the set that was live is pushed here
 * verbatim and the replacement becomes the new live `Transaction.splits`. Superseded sets
 * are audit history and are never destroyed by a later edit.
 *
 * `currency` is deliberately NOT stored on a leg or on a set. vNext A2 requires every leg
 * to share the parent's `currency`, so storing it here would create a second source of
 * truth that could disagree with the parent. It is derived from the parent instead.
 */
export interface SupersededAllocationSet {
  /** The version number this set held while it was the live set. */
  version: number;
  /** The legs exactly as they were when the set was superseded. */
  legs: TransactionSplit[];
  /** ISO datetime at which this set stopped being live. */
  supersededAt: string;
}

export const CORRECTION_ROLES = ['reversal', 'replacement'] as const;
export type CorrectionRole = (typeof CORRECTION_ROLES)[number];

/**
 * Provenance for a row that exists only to correct a `reconciled` row (C6 I4.5,
 * vNext S2; owner decision D4-A, 2026-09-02).
 *
 * A reconciled transaction is a lock: it is never mutated in place. A correction appends
 * exactly two rows per corrected original — a `reversal` that undoes the recorded amount
 * and a `replacement` that states the corrected facts — both carrying the same
 * `correctionGroupId` so they can only ever be read, reversed or reported as a unit.
 *
 * The `unreconcile + amend` alternative that vNext S2 also specifies is NOT implemented:
 * D4 chose reversal + replacement, so only one workflow exists in code.
 */
export interface CorrectionLink {
  /** The reconciled transaction this row corrects. Never mutated by the correction. */
  correctsTransactionId: string;
  /** Whether this row undoes the original amount or states the corrected facts. */
  role: CorrectionRole;
  /**
   * Groups every reversal and replacement emitted by one correction. A transfer
   * correction covers both legs, so a group can hold four rows (C6 I4.6, vNext T5).
   */
  correctionGroupId: string;
  /** Owner-supplied reason, stored verbatim. Never generated by an LLM or inferred. */
  reason: string;
}

/**
 * Provenance carried over from the imported master ledger (LEDGER_SCHEMA.md).
 *
 * The six required fields were here before Step 6. The optional fields were added in Step 6 to
 * support the candidate staging tier; they are absent on rows created by older code, which is
 * fine because the schema validator treats them as optional.
 */
export interface ImportInfo {
  // --- original six fields (Step 2a) ---
  duplicateKey: string;
  sourceFile: string;
  sourcePageOrSheet: string;
  extractionMethod: 'parser' | 'ocr' | 'manual';
  confidenceScore: number;
  confidenceReason: string;
  // --- staging-tier fields added in Step 6 (all optional for backward-compatibility) ---
  /** Groups all rows that arrived in the same import session or batch. */
  batchId?: string;
  /**
   * Deterministic hash of the row's financially consequential fields (date, amount, payee,
   * account, direction, currency). Used as a stable dedup key independent of row order.
   * Never includes mutable fields (memo, category) so an edit cannot change the fingerprint.
   */
  contentHash?: string;
  /** The parser version that produced this row, so a re-parse at a newer version can be detected. */
  parserVersion?: number;
  /**
   * How the row arrived at the ingestion boundary.
   *  - `csv` — uploaded master-ledger file
   *  - `telegram` — extracted from a Telegram notification
   *  - `sms` — extracted from an SMS notification
   *  - `email` — extracted from an email notification
   *  - `manual` — user typed it in
   */
  sourceType?: 'csv' | 'telegram' | 'sms' | 'email' | 'manual';
  /** Original transaction ID in the source system (bank reference, Telegram message-id, etc.). */
  sourceTransactionId?: string;
  /** Original account identifier in the source system (account number, card last-4, etc.). */
  sourceAccountId?: string;
  /** Bank or statement reference number, verbatim from the source. */
  statementReference?: string;
  /**
   * Payee name after normalization (lower-cased, merchant-suffix removed, whitespace collapsed).
   * Stored alongside the raw payee so fuzzy dedup and display can use both.
   */
  normalizedPayee?: string;
}

export interface Transaction {
  id: string;
  accountId: string;
  /** Transaction date, ISO YYYY-MM-DD. */
  date: string;
  payee: string;
  /** Budget category id; null = uncategorized or a transfer. */
  categoryId: string | null;
  memo: string;
  /** Signed milliunits: outflow negative, inflow positive. */
  amount: Money;
  /**
   * Currency the amount was ACTUALLY transacted in (C6 I1.2). Usually equals the
   * account's currency; a foreign purchase on a domestic card is the case where it
   * does not. Required, never inferred from the account.
   */
  currency: CurrencyCode;
  cleared: ClearedStatus;
  /** False until the user approves an imported transaction. */
  approved: boolean;
  /** Transfer linkage: the peer account and mirrored transaction. */
  transferAccountId: string | null;
  transferTransactionId: string | null;
  /** Split legs; null for simple transactions. This is always the LIVE allocation set. */
  splits: TransactionSplit[] | null;
  /** Import provenance; null for manually entered transactions. */
  importInfo: ImportInfo | null;
  // --- versioned allocations + reconciled lock, added in Step 4 (Contract 6 Phase 6.4) ---
  /**
   * Version of the live `splits` set. Absent means 0 — the set has never been superseded.
   * Optional rather than required so pre-Step-4 rows still parse unchanged, and absent so a
   * row that was never edited does not carry a field whose only value is the default.
   */
  allocationSetVersion?: number;
  /**
   * Append-only history of allocation sets that were superseded by an edit (C6 I4.4).
   * Absent means no set was ever superseded. Never truncated by application code.
   */
  supersededAllocations?: SupersededAllocationSet[];
  /**
   * Set only on rows that exist to correct a reconciled row (C6 I4.5). `null` and absent
   * both mean "this is an ordinary row, not part of a correction".
   */
  correction?: CorrectionLink | null;
}

/**
 * Version of the live allocation set. Absence means version 0 (C6 I4.3).
 *
 * Read through this accessor rather than the raw field so the "absent means 0" convention
 * has exactly one implementation.
 */
export function allocationVersionOf(t: Pick<Transaction, 'allocationSetVersion'>): number {
  return t.allocationSetVersion ?? 0;
}

/** Retained superseded allocation sets, oldest first. Never null (C6 I4.4). */
export function supersededAllocationsOf(
  t: Pick<Transaction, 'supersededAllocations'>,
): readonly SupersededAllocationSet[] {
  return t.supersededAllocations ?? [];
}

/** True when this row exists only to reverse or replace a reconciled row (C6 I4.5). */
export function isCorrectionRow(t: Pick<Transaction, 'correction'>): boolean {
  return t.correction != null;
}

/** Non-negative outflow magnitude (0 for inflows). */
export function outflowOf(t: Pick<Transaction, 'amount'>): Money {
  return t.amount < 0 ? -t.amount : 0;
}

/** Non-negative inflow magnitude (0 for outflows). */
export function inflowOf(t: Pick<Transaction, 'amount'>): Money {
  return t.amount > 0 ? t.amount : 0;
}
